//! On-disk file generators for the `fraisier` CLI.
//!
//! This crate owns the *content* fraisier writes to a user's project and hosts:
//! the [`starter_config`] that `fraisier init` produces, and the
//! [`generate`](generate::generate) systemd / socket / nginx / CI templates.
//! Generation performs no I/O — it returns [`GeneratedFile`]s; each carries the
//! [`MARKER`] header so install/prune can recognise fraisier's own files and a
//! prune never touches a file fraisier did not generate.

use std::path::PathBuf;

mod generate;
mod install;

pub use generate::{generate, generate_scheduled, GeneratedFile, MARKER};
pub use install::{install, install_targets, prune, prune_plan, write_tree};

/// An error from generating, installing, or pruning scaffold files.
#[derive(Debug, thiserror::Error)]
pub enum ScaffoldError {
    /// A config field required to render the templates is missing.
    #[error("[{section}].{field} is required to scaffold")]
    MissingField {
        /// The config section the field belongs to.
        section: &'static str,
        /// The missing field.
        field: &'static str,
    },
    /// A config field is present but its value is invalid.
    #[error("[{section}].{field}: {message}")]
    InvalidField {
        /// The config section the field belongs to.
        section: &'static str,
        /// The offending field.
        field: &'static str,
        /// Why the value is invalid.
        message: String,
    },
    /// Writing a generated/installed file failed.
    #[error("writing {path}: {source}")]
    Write {
        /// The destination path.
        path: PathBuf,
        /// The underlying I/O error.
        source: std::io::Error,
    },
    /// Reading a directory during prune failed.
    #[error("reading {path}: {source}")]
    Read {
        /// The directory being scanned.
        path: PathBuf,
        /// The underlying I/O error.
        source: std::io::Error,
    },
}

/// The starter `fraisier.toml` that `fraisier init` writes into a fresh project.
///
/// It is a single-host release deploy with inline guidance on every section. The
/// values are placeholders to edit, but the document validates clean against
/// [`fraisier_config`](https://docs.rs/fraisier-config) with no warnings, so a
/// freshly-`init`ed project passes `fraisier validate-config` before any edits.
#[must_use]
pub const fn starter_config() -> &'static str {
    STARTER_CONFIG
}

/// The starter `fraisier.toml` document. Edit-me placeholders, valid as written.
const STARTER_CONFIG: &str = r#"# fraisier.toml — generated by `fraisier init`.
#
# Atomic, rollback-safe deploys. Edit the placeholders below, then run:
#   fraisier validate-config
#   fraisier deploy --app-version <version>
# Full reference: https://fraiseql.dev

[deploy]
# The deployable's name and the environment this file targets.
name = "myapp"
environment = "production"

[artifact]
# Where the build comes from: "release" (URL + checksum), "git", or "local".
source = "release"
# `{version}` is substituted with the value of `deploy --app-version`.
release_url = "https://example.com/myapp-{version}.tar.gz"
checksum_url = "https://example.com/myapp-{version}.tar.gz.sha256"
# The "current" symlink that activation atomically swaps to the new release.
active_path = "/srv/myapp/current"

[migration]
# Migration adapter: "confiture", "command", or an IPC adapter found on PATH.
adapter = "confiture"
# The *name* of the env var holding the database DSN — never the value itself.
database_url_env = "MYAPP_DATABASE_URL"
migrations_path = "./migrations"

[service]
# Service manager: "systemd", "rc", or "docker-compose".
adapter = "systemd"
unit = "myapp.service"

[health]
# Post-restart health probe; the deploy commits only once this passes.
adapter = "http"
url = "http://127.0.0.1:8080/health"
expected_status = 200
"#;

#[cfg(test)]
mod tests {
    use fraisier_config::DeployConfig;

    #[test]
    fn starter_config_validates_clean_with_no_warnings() {
        let cfg = DeployConfig::from_toml_str(super::starter_config())
            .expect("the starter config parses");
        let report = cfg.validate();
        assert!(
            report.ok(),
            "the starter config must validate clean:\n{report}"
        );
        assert_eq!(
            report.warnings().count(),
            0,
            "a good starter config should carry no caveats:\n{report}"
        );
    }
}
